### ISSUE TITLE
UI no longer active after component rename

### ISSUE THREAD

**Issue by yessenbayev** [yapms/YAPms#323] opened 2023-08-31 03:03 UTC
Under the "President" view if I edit the name of the party, (for example, rename "Democrat" to "Democrats") the UI is no longer active.

From the log, it is due to an unhandled promise. I paste the JavaScript Console log below

[Error] Unhandled Promise Rejection: InvalidStateError: The object is in an invalid state.
	at (scheduler.1babeacc.js:1:9185)
	promiseReactionJob

Platform: Safari Version 16.2 (17614.3.7.1.7, 17614)

**Comment by Flizzyclone** [comment] 2023-09-02 03:35
for my reference: https://discord.com/channels/1038861619540795512/1038875719666765954/1147372940430676062

this is caused by some weird stuff related to closing modals using dialogs. seems like when we update a store associated w/ a modal, the modal tries to figure out if it should close or not and in the process goes through too many updates at once.

**Closed as completed** 2023-09-06 00:36 UTC
